# Header Menu
menu:
  Home: /
  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/zhangxishuo
  twitter: https://twitter.com/zhangxishuo
  facebook: https://www.facebook.com/ptsteadman
  rss: atom.xml
  linkedin: https://linkedin.com/in/ptsteadman
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: zhangxishuo # twitter username without the @
default_author: Anonymous

about: 河北工业大学梦云智软件开发团队
phone: 17695552766
email: zhangxishuo1998@gmail.com
address_1: 河北工业大学 教师公寓
address_2: 28号楼 1单元
address_3: 301室
skype: zhangxishuo1998
lat: 39.236256 
long: 117.051279 
